[package]
name = "distrobox_boost"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "distrobox-boost"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
lazy_static = "1.4.0"
